import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactX from 'eslint-plugin-react-x'
import reactDom from 'eslint-plugin-react-dom'
import next from '@next/eslint-plugin-next'
import tseslint from 'typescript-eslint'
import prettier from 'eslint-config-prettier'

export default tseslint.config(
  {
    ignores: [
      '.next',
      'node_modules',
      'coverage',
      'next-env.d.ts',
      // Reference copies of the house style, kept for provenance. Not project source —
      // and ESLint 10 would otherwise try to load configs/eslint.config.js as a
      // nested config, which depends on Vite-only plugins this project does not install.
      'configs/**',
      // Generated by the Supabase CLI (`pnpm db:types`).
      'src/lib/supabase/database.types.ts',
    ],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      // Type-aware linting
      ...tseslint.configs.recommendedTypeChecked,
      // React-specific type-aware rules
      reactX.configs['recommended-typescript'],
      reactDom.configs.recommended,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      // Server Components, Route Handlers and proxy.ts all run in Node.
      globals: { ...globals.browser, ...globals.node },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      '@next/next': next,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...next.configs.recommended.rules,
      ...next.configs['core-web-vitals'].rules,
    },
  },
  // Test files run under Vitest globals (`test.globals` is enabled).
  {
    files: ['**/*.test.{ts,tsx}', 'vitest.setup.ts'],
    languageOptions: {
      globals: globals.vitest,
    },
  },
  // Disable ESLint formatting rules that conflict with Prettier (keep last)
  prettier,
)
